export const boxes = [
    {
        id: 1,
        img: "https://picsum.photos/500/300",
        mainHeading: "Back-End",
        description: "Backend development(also stylized as back-end or back end development)",
        courseNo: 4,
        lessons: 10,
        durationHour: 20,
        durationMinutes: 45,
    },
    {
        id: 2,
        img: "https://picsum.photos/500/299",
        mainHeading: "Front-End",
        description: "Frontend development(also stylized as front-end or front end development)",
        courseNo: 5,
        lessons: 13,
        durationHour: 11,
        durationMinutes: 40,
    },
    {
        id: 3,
        img: "https://picsum.photos/499/300",
        mainHeading: "Graphic Designing",
        description: "Graphic designing course which gives you idea of adobe applications.",
        courseNo: 4,
        lessons: 10,
        durationHour: 20,
        durationMinutes: 45,
    },
    {
        id: 4,
        img: "https://picsum.photos/501/300",
        mainHeading: "Digital Marketing",
        description: "You will learn advances topic like SEO and website ranking methods.",
        courseNo: 4,
        lessons: 10,
        durationHour: 20,
        durationMinutes: 45,
    },
]